Parameters:

  BucketName:
    Type: String
    Description: S3 bucket name that hosts Lambda content

  Architecture:
    Type: String
    Description: Executable architecture for the Lambda function
    AllowedValues:
      - x86_64
      - arm64

Outputs:
  InvokeURL:
    Description: "HTTP API URL"
    Value: !Sub "https://${API}.execute-api.${AWS::Region}.amazonaws.com/${APIStage}/passkeys"

Resources:
  
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UserPoolName: !Sub ${AWS::StackName}UserPool
      AutoVerifiedAttributes:
        - email
      LambdaConfig:
        DefineAuthChallenge: !Sub "${AuthLambda.Arn}"
        CreateAuthChallenge: !Sub "${AuthLambda.Arn}"
        VerifyAuthChallengeResponse: !Sub "${AuthLambda.Arn}"
      Schema:
        - AttributeDataType: String
          Name: publicKeyCred
          Mutable: true
          StringAttributeConstraints:
            MaxLength: 1024

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${AWS::StackName}TestClientApp
      GenerateSecret: false
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      WriteAttributes:
        - custom:publicKeyCred
        - email
        - name
      ReadAttributes:
        - email
        - name

  AuthLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SwiftPasskeyAuthorizerFunctionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"

  AuthLambda:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - !Ref Architecture
      Code:
        S3Bucket: !Ref BucketName
        S3Key: "SwiftPasskeyAuthorizerFunction.zip"
      FunctionName: SwiftPasskeyAuthorizer
      Handler: SwiftPasskeyAuthorizer
      PackageType: Zip
      Role: !Sub "${AuthLambdaRole.Arn}"
      Runtime: "provided.al2"

  AuthLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub "${AuthLambda.Arn}"
      Principal: cognito-idp.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub "${UserPool.Arn}"

  APILambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SwiftPasskeyServerFunctionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"

  APILambda:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - !Ref Architecture
      Code:
        S3Bucket: !Ref BucketName
        S3Key: SwiftPasskeyServerFunction.zip
      FunctionName: SwiftPasskeyServer
      Handler: SwiftPasskeyServer
      PackageType: Zip
      Role: !Sub "${APILambdaRole.Arn}"
      Runtime: "provided.al2"

  LambdaAPIPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub "${APILambda.Arn}"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${API}/*/*/*"

  API:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Description: "Swift Passkey HTTP API"
      Name: SwiftPasskey
      ProtocolType: HTTP
      Version: 1

  APIIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref API
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "${APILambda.Arn}"
      PayloadFormatVersion: "2.0"

  APIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref API
      RouteKey: "GET /register"
      Target: !Sub "integrations/${APIIntegration}"

  APIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref API
      RouteKey: "POST /register"
      Target: !Sub "integrations/${APIIntegration}"

  APIStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref API
      AutoDeploy: true
      Description: "API Test Deployment"
      StageName: Test
